# Generated by Django 3.2.25 on 2026-06-15 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada'), ('C', 'Completada')], default='P', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_name', models.CharField(max_length=180, verbose_name='Nombre del producto')),
                ('product_sku', models.CharField(max_length=80, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='products.product', verbose_name='Producto')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotationrequest', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de cotización',
                'verbose_name_plural': 'Items de cotización',
                'ordering': ['pk'],
            },
        ),
    ]
