# Generated by Django 3.2.25 on 2026-06-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequest',
            name='status',
        ),
    ]
